"""Cap-spelling corpus: 111 labelled ways to bound a list, and 29 ways that are not.

WHERE THIS CAME FROM. Two adversarial fix rounds on hooks/capped_report.py built a detector
that enumerated Python syntaxes. That design was reverted: the set of syntaxes is unbounded,
so the work never terminated, and an unenumerated shape was reported CLEAN - it failed OPEN,
which is the exact failure unbluff exists to catch. See docs/V131_REVIEW_PLAN.md P14.

WHY THE CORPUS SURVIVED THE DETECTOR. Each entry is a concrete module plus a verdict on
whether a cap guard MUST flag it. That makes it a grader, not an implementation: any guard,
however built, can be scored against it. The 29 negative controls matter as much as the 111
positives - a guard that flags everything scores perfectly on the positives alone.

CONTRACT
  ENTRY = (name, rel_path, must_flag, source)
    name      short id, unique
    rel_path  where to plant it, so directory-scoped guards can be exercised
    must_flag True  -> a correct guard reports this as an unrouted cap
              False -> a correct guard stays quiet; flagging it is a false positive
    source    the complete module text

APPEND-ONLY. Removing an entry, or flipping a must_flag, silently narrows every guard graded
against it - the same class of regression that caused the revert. Add; do not edit or delete.
"""

ENTRIES = (
    ('plain_assign_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('annotated_assign_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS: int = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('augassign_adjusted_bound',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 8\nMAX_BULLETS += 4\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('walrus_bound',
     'hooks/f.py',
     True,
     "import os\nif (MAX_BULLETS := int(os.environ.get('N', '12'))) > 0:\n    pass\ndef report(xs):\n    return xs[:MAX_BULLETS]\n"),
    ('tuple_target_bound',
     'hooks/f.py',
     True,
     'MAX_BULLETS, MAX_ROWS = 12, 40\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('list_target_bound',
     'hooks/f.py',
     True,
     '[MAX_BULLETS] = [12]\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('from_import_bound',
     'hooks/f.py',
     True,
     'from limits import MAX_BULLETS\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('import_attribute_bound',
     'hooks/f.py',
     True,
     'import limits\ndef report(xs):\n    return xs[:limits.MAX_BULLETS]\n'),
    ('alias_bound',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\nSHOWN = MAX_BULLETS\ndef report(xs):\n    return xs[:SHOWN]\n'),
    ('arithmetic_bound',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS - 1]\n'),
    ('class_attr_bound',
     'hooks/f.py',
     True,
     'class Limits:\n    MAX_BULLETS = 12\ndef report(xs):\n    return xs[:Limits.MAX_BULLETS]\n'),
    ('dict_config_bound',
     'hooks/f.py',
     True,
     "LIMITS = {'bullets': 12}\ndef report(xs):\n    return xs[:LIMITS['bullets']]\n"),
    ('non_max_constant_name',
     'hooks/f.py',
     True,
     'BULLET_LIMIT = 12\ndef report(xs):\n    return xs[:BULLET_LIMIT]\n'),
    ('negative_lower_tail_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[-MAX_BULLETS:]\n'),
    ('del_tail',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    out = list(xs)\n    del out[MAX_BULLETS:]\n    return out\n'),
    ('islice',
     'hooks/f.py',
     True,
     'import itertools\nMAX_BULLETS = 12\ndef report(xs):\n    return list(itertools.islice(xs, MAX_BULLETS))\n'),
    ('slice_object_call',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[slice(0, MAX_BULLETS)]\n'),
    ('comprehension_index_guard',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return [x for i, x in enumerate(xs) if i < MAX_BULLETS]\n'),
    ('pop_until_under_cap',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(out):\n    while len(out) > MAX_BULLETS:\n        out.pop()\n    return out\n'),
    ('heapq_nlargest',
     'hooks/f.py',
     True,
     'import heapq\nMAX_BULLETS = 12\ndef report(xs):\n    return heapq.nlargest(MAX_BULLETS, xs)\n'),
    ('sorted_then_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return sorted(xs)[:MAX_BULLETS]\n'),
    ('function_local_bound',
     'hooks/f.py',
     True,
     'def report(xs):\n    MAX_BULLETS = 12\n    return xs[:MAX_BULLETS]\n'),
    ('two_sites_one_constant',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\ndef other(ys):\n    return ys[:MAX_BULLETS]\n'),
    ('unparseable_module',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs)\n    return xs[:MAX_BULLETS]\n'),
    ('module_in_subdirectory',
     'hooks/lib/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('module_in_tools',
     'tools/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('module_in_skill_scripts',
     'skills/s/scripts/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('break_ge_in_body',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_ITEMS: break\n        out.append(x)\n'),
    ('lowercase_cap_parameter',
     'hooks/f.py',
     True,
     'def scan(xs, cap: int = 15):\n    out = []\n    for x in xs:\n        if len(out) >= cap: break\n        out.append(x)\n    return out\n'),
    ('reversed_comparison_break',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if MAX_ITEMS <= len(out): break\n        out.append(x)\n'),
    ('break_in_orelse',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) < MAX_ITEMS: out.append(x)\n        else: break\n'),
    ('break_nested_in_with',
     'hooks/f.py',
     True,
     'import contextlib\nMAX_ITEMS = 10\ndef scan(xs, out):\n    for x in xs:\n        if len(out) >= MAX_ITEMS:\n            with contextlib.suppress(OSError): break\n'),
    ('return_instead_of_break',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_ITEMS: return out\n        out.append(x)\n'),
    ('continue_instead_of_break',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_ITEMS: continue\n        out.append(x)\n'),
    ('while_test_cap',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(it):\n    out = []\n    while len(out) < MAX_ITEMS:\n        out.append(next(it))\n    return out\n'),
    ('takewhile',
     'hooks/f.py',
     True,
     'import itertools\nMAX_ITEMS = 10\ndef scan(xs):\n    return list(itertools.takewhile(lambda p: p[0] < MAX_ITEMS, enumerate(xs)))\n'),
    ('break_on_attribute_bound',
     'hooks/f.py',
     True,
     'import limits\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= limits.MAX_ITEMS: break\n        out.append(x)\n'),
    ('break_on_counter_variable',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    n = 0\n    for x in xs:\n        n += 1\n        if n > MAX_ITEMS: break\n'),
    ('break_with_boolean_op',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs, stop):\n    out = []\n    for x in xs:\n        if stop or len(out) >= MAX_ITEMS: break\n        out.append(x)\n'),
    ('break_on_arithmetic_bound',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for i, x in enumerate(xs):\n        if i >= MAX_ITEMS - 1: break\n        out.append(x)\n'),
    ('zip_range_cap',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    return [x for _, x in zip(range(MAX_ITEMS), xs)]\n'),
    ('break_via_walrus_counter',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs):\n    out = []\n    for x in xs:\n        if (n := len(out)) >= MAX_ITEMS: break\n        out.append(x)\n'),
    ('break_in_nested_loop',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(gs, out):\n    for g in gs:\n        for x in g:\n            if len(out) >= MAX_ITEMS: break\n            out.append(x)\n'),
    ('neg_routed_through_render',
     'hooks/f.py',
     False,
     'import capped_report\nMAX_BULLETS = 12\ndef report(xs):\n    return capped_report.render(xs, MAX_BULLETS)\n'),
    ('neg_routed_through_keep',
     'hooks/f.py',
     False,
     'import capped_report\nMAX_ITEMS = 10\ndef scan(xs):\n    kept, total = capped_report.keep(xs, MAX_ITEMS)\n    return capped_report.render(kept, MAX_ITEMS, total=total)\n'),
    ('neg_bound_exemption_collection',
     'hooks/numbers_match_on_write.py',
     False,
     'MAX_FINDINGS_TRACKED = 200\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_FINDINGS_TRACKED: break\n        out.append(x)\n'),
    ('display_under_a_collection_exemption',
     'hooks/numbers_match_on_write.py',
     True,
     'MAX_FINDINGS_TRACKED = 200\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_FINDINGS_TRACKED: break\n        out.append(x)\ndef build_message(sources):\n    return sources[:MAX_FINDINGS_TRACKED]\n'),
    ('display_in_the_exempted_function',
     'hooks/numbers_match_on_write.py',
     True,
     'MAX_FINDINGS_TRACKED = 200\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_FINDINGS_TRACKED: break\n        out.append(x)\n    return out[:MAX_FINDINGS_TRACKED]\n'),
    ('second_cap_under_an_approved_exemption',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 5\ndef scan(xs, ys):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_ITEMS: break\n        out.append(x)\n    for y in ys:\n        if len(out) >= MAX_ITEMS: break\n        out.append(y)\n    return out\n'),
    ('neg_max_used_for_retries',
     'hooks/f.py',
     False,
     "MAX_RETRIES = 3\ndef call(fn):\n    for _a in range(MAX_RETRIES):\n        return fn()\n    raise RuntimeError('gave up')\n"),
    ('neg_max_used_as_loud_rejection',
     'hooks/f.py',
     False,
     "MAX_ROWS = 500\ndef load(rows):\n    if len(rows) > MAX_ROWS:\n        raise ValueError('too many rows')\n    return rows\n"),
    ('neg_structural_slice_not_a_cap',
     'hooks/f.py',
     False,
     'MAX_BULLETS = 12\ndef head_tail(parts):\n    return parts[:2], parts[2:]\n'),
    ('scalar_slice_without_a_roster_entry',
     'hooks/f.py',
     True,
     'MAX_FILE_BYTES = 200000\ndef read_capped(fh):\n    text = fh.read()\n    return text[:MAX_FILE_BYTES]\n'),
    ('size_skip_by_getsize',
     'hooks/f.py',
     True,
     'import os\nMAX_FILE_BYTES = 200000\ndef index_sources(paths):\n    out = []\n    for p in paths:\n        if os.path.getsize(p) > MAX_FILE_BYTES:\n            continue\n        out.append(p)\n    return out\n'),
    ('size_skip_on_a_loop_variable',
     'hooks/f.py',
     True,
     'MAX_LEN = 80\ndef scan(lines):\n    out = []\n    for line in lines:\n        if len(line) > MAX_LEN:\n            continue\n        out.append(line)\n    return out\n'),
    ('neg_scalar_slice_rostered',
     'hooks/f.py',
     False,
     'MAX_FILE_BYTES = 200000\ndef read_capped(fh):\n    text = fh.read()\n    return text[:MAX_FILE_BYTES]\n'),
    ('neg_size_skip_rostered',
     'hooks/f.py',
     False,
     'import os\nMAX_FILE_BYTES = 200000\ndef index_sources(paths):\n    out = []\n    for p in paths:\n        if os.path.getsize(p) > MAX_FILE_BYTES:\n            continue\n        out.append(p)\n    return out\n'),
    ('read_derived_input_window',
     'hooks/f.py',
     True,
     "MAX_TAIL_LINES = 120\ndef read_tail_lines(path, max_lines=MAX_TAIL_LINES):\n    with open(path, 'rb') as handle:\n        data = handle.read()\n    lines = data.decode('utf-8', errors='replace').splitlines()\n    return lines[-max_lines:]\n"),
    ('neg_read_derived_input_window_rostered',
     'hooks/f.py',
     False,
     "MAX_TAIL_LINES = 120\ndef read_tail_lines(path, max_lines=MAX_TAIL_LINES):\n    with open(path, 'rb') as handle:\n        data = handle.read()\n    lines = data.decode('utf-8', errors='replace').splitlines()\n    return lines[-max_lines:]\n"),
    ('assembled_list_is_not_a_read_window',
     'hooks/f.py',
     True,
     'MAX_TAIL_LINES = 120\ndef report(xs):\n    out = []\n    for x in xs:\n        out.append(x)\n    return out[-MAX_TAIL_LINES:]\n'),
    ('display_cap_on_a_loop_variable',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(groups):\n    for group in groups:\n        return group[:MAX_BULLETS]\n'),
    ('neg_retry_while',
     'hooks/f.py',
     False,
     "MAX_RETRIES = 3\ndef call(fn):\n    n = 0\n    while n < MAX_RETRIES:\n        n += 1\n        try:\n            return fn()\n        except OSError:\n            pass\n    raise RuntimeError('gave up')\n"),
    ('neg_poll_while',
     'hooks/f.py',
     False,
     'import time\nMAX_WAIT_SECONDS = 30\ndef poll(ready):\n    waited = 0\n    while waited < MAX_WAIT_SECONDS:\n        if ready():\n            return True\n        time.sleep(1)\n        waited += 1\n    return False\n'),
    ('neg_depth_while',
     'hooks/f.py',
     False,
     'MAX_DEPTH = 5\ndef root_of(node):\n    depth = 0\n    while depth < MAX_DEPTH and node.parent is not None:\n        node = node.parent\n        depth += 1\n    return node\n'),
    ('neg_scalar_shrink_while',
     'hooks/f.py',
     False,
     'MAX_BYTES = 100\ndef shrink(text):\n    while len(text) > MAX_BYTES:\n        text = text[:-1]\n    return text\n'),
    ('param_default_bound',
     'hooks/f.py',
     True,
     'MAX_LINES = 50\ndef report(xs, max_lines=MAX_LINES):\n    return xs[:max_lines]\n'),
    ('param_default_bound_collection',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\ndef scan(xs, budget=MAX_ITEMS):\n    out = []\n    for x in xs:\n        if len(out) >= budget:\n            break\n        out.append(x)\n    return out\n'),
    ('neg_param_default_not_a_bound',
     'hooks/f.py',
     False,
     "DEFAULT_PREFIX = '- '\ndef report(xs, prefix=DEFAULT_PREFIX):\n    return [prefix + x for x in xs]\n"),
    ('int_display_annotated_list_param',
     'hooks/f.py',
     True,
     'def build_message(problems: list[str]):\n    return problems[:12]\n'),
    ('int_display_local_accumulator',
     'hooks/f.py',
     True,
     'def build_message(xs):\n    problems = []\n    for x in xs:\n        problems.append(x)\n    return problems[:12]\n'),
    ('int_collection_break',
     'hooks/f.py',
     True,
     'def scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= 10:\n            break\n        out.append(x)\n    return out\n'),
    ('int_collection_return',
     'hooks/f.py',
     True,
     'def scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= 10:\n            return out\n        out.append(x)\n    return out\n'),
    ('int_collection_reversed_operands',
     'hooks/f.py',
     True,
     'def scan(xs):\n    out = []\n    for x in xs:\n        if 10 <= len(out):\n            break\n        out.append(x)\n    return out\n'),
    ('int_collection_while',
     'hooks/f.py',
     True,
     'def scan(it):\n    out = []\n    while len(out) < 10:\n        out.append(next(it))\n    return out\n'),
    ('int_del_tail',
     'hooks/f.py',
     True,
     'def report(xs):\n    out = list(xs)\n    del out[12:]\n    return out\n'),
    ('int_sorted_then_slice',
     'hooks/f.py',
     True,
     'def report(xs):\n    return sorted(xs)[:12]\n'),
    ('int_comprehension_assigned_base',
     'hooks/f.py',
     True,
     'def report(xs):\n    findings = [f for f in xs if f]\n    return findings[:12]\n'),
    ('int_islice',
     'hooks/f.py',
     True,
     'import itertools\ndef report(xs):\n    return list(itertools.islice(xs, 12))\n'),
    ('int_zip_range',
     'hooks/f.py',
     True,
     'def scan(xs):\n    return [x for _, x in zip(range(10), xs)]\n'),
    ('int_takewhile',
     'hooks/f.py',
     True,
     'import itertools\ndef scan(xs):\n    return list(itertools.takewhile(lambda p: p[0] < 10, enumerate(xs)))\n'),
    ('int_list_of_dict_then_slice',
     'hooks/f.py',
     True,
     'def report(d):\n    return list(d)[:12]\n'),
    ('int_comprehension_index_guard',
     'hooks/f.py',
     True,
     'def report(xs: list):\n    return [x for i, x in enumerate(xs) if i < 12]\n'),
    ('neg_int_str_truncation_opaque',
     'hooks/f.py',
     False,
     "def warn(msg):\n    return '[hook] ' + msg[:120]\n"),
    ('neg_int_str_truncation_proven',
     'hooks/f.py',
     False,
     'def warn(path):\n    text = open(path).read()\n    return text[:120]\n'),
    ('neg_int_hash_prefix',
     'hooks/f.py',
     False,
     'import hashlib\ndef sid(b):\n    return hashlib.sha256(b).hexdigest()[:12]\n'),
    ('neg_int_positional_head',
     'hooks/f.py',
     False,
     'def split_entry(entry):\n    return entry[:2], entry[2:]\n'),
    ('neg_int_argv',
     'hooks/f.py',
     False,
     'import sys\ndef args():\n    return sys.argv[1:]\n'),
    ('neg_int_arity_filter',
     'hooks/f.py',
     False,
     'def load(rows):\n    out = []\n    for entry in rows:\n        if len(entry) < 4:\n            continue\n        out.append(entry)\n    return out\n'),
    ('neg_int_index_bounds_check',
     'hooks/f.py',
     False,
     'def at(values, i):\n    if 0 <= i < len(values):\n        return values[i]\n    return None\n'),
    ('neg_int_year_filter',
     'hooks/f.py',
     False,
     'def years(vals):\n    out = []\n    for value in vals:\n        if 1900 <= value <= 2099:\n            out.append(value)\n    return out\n'),
    ('neg_int_sentinel_while',
     'hooks/f.py',
     False,
     "def spans(text):\n    pos = text.find('x')\n    while pos != -1:\n        pos = text.find('x', pos + 1)\n    return pos\n"),
    ('neg_int_rolling_retention',
     'hooks/f.py',
     False,
     'def remember(history, item):\n    history.append(item)\n    return history[-200:]\n'),
    ('neg_int_equality_filter',
     'hooks/f.py',
     False,
     'def picked(xs):\n    return [x for i, x in enumerate(xs) if i == 3]\n'),
    ('neg_int_split_then_index',
     'hooks/f.py',
     False,
     "def head(line):\n    parts = line.split(':')\n    return parts[:1]\n"),
    ('neg_int_decrementing_while',
     'hooks/f.py',
     False,
     'def back_up(start):\n    while start - 1 >= 0:\n        start -= 1\n    return start\n'),
    ('neg_int_below_the_positional_floor',
     'hooks/f.py',
     False,
     'def first_few(xs):\n    kept = list(xs)\n    return kept[:3]\n'),
    ('collection_cap_moved_into_a_same_named_method',
     'hooks/numbers_match_on_write.py',
     True,
     'MAX_FINDINGS_TRACKED = 200\nclass LegacyScanner:\n    def run(self, xs):\n        out = []\n        for x in xs:\n            if len(out) >= MAX_FINDINGS_TRACKED:\n                break\n            out.append(x)\n        return out\n'),
    ('neg_collection_cap_in_the_approved_function',
     'hooks/numbers_match_on_write.py',
     False,
     'MAX_FINDINGS_TRACKED = 200\ndef run(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_FINDINGS_TRACKED:\n            break\n        out.append(x)\n    return out\n'),
    ('annotated_binding_behind_a_plain_alias',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\nshown: int = MAX_BULLETS\ndef report(xs):\n    return xs[:shown]\n'),
    ('walrus_binding_behind_a_plain_alias',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\nif (shown := MAX_BULLETS) > 0:\n    pass\ndef report(xs):\n    return xs[:shown]\n'),
    ('imported_bound_behind_a_plain_alias',
     'hooks/f.py',
     True,
     'from limits import MAX_BULLETS as shown\ndef report(xs):\n    return xs[:shown]\n'),
    ('star_import_display',
     'hooks/f.py',
     True,
     'from limits import *\ndef report(xs):\n    return xs[:MAX_BULLETS]\n'),
    ('star_import_collection',
     'hooks/f.py',
     True,
     'from limits import *\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_ITEMS:\n            break\n        out.append(x)\n    return out\n'),
    ('star_import_islice',
     'hooks/f.py',
     True,
     'from itertools import islice\nfrom limits import *\ndef report(xs):\n    return list(islice(xs, MAX_ITEMS))\n'),
    ('star_import_plus_an_unrelated_local_cap',
     'hooks/f.py',
     True,
     'from limits import *\nMAX_LOCAL = 3\ndef report(xs, ys):\n    a = xs[:MAX_LOCAL]\n    b = ys[:MAX_BULLETS]\n    return a, b\n'),
    ('nlargest_keyword_args',
     'hooks/f.py',
     True,
     'import heapq\nMAX_BULLETS = 12\ndef report(xs):\n    return heapq.nlargest(n=MAX_BULLETS, iterable=xs)\n'),
    ('nsmallest_keyword_args',
     'hooks/f.py',
     True,
     'import heapq\nMAX_BULLETS = 12\ndef report(xs):\n    return heapq.nsmallest(n=MAX_BULLETS, iterable=xs)\n'),
    ('islice_behind_a_callee_alias',
     'hooks/f.py',
     True,
     'from itertools import islice as take\nMAX_BULLETS = 12\ndef report(xs):\n    return list(take(xs, MAX_BULLETS))\n'),
    ('deque_maxlen',
     'hooks/f.py',
     True,
     'import collections\nMAX_BULLETS = 12\ndef report(xs):\n    return collections.deque(xs, maxlen=MAX_BULLETS)\n'),
    ('alias_via_conditional',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\ndef report(xs, verbose):\n    shown = MAX_BULLETS if verbose else 5\n    return xs[:shown]\n'),
    ('alias_via_tuple_unpack',
     'hooks/f.py',
     True,
     "MAX_BULLETS = 12\nSHOWN, PREFIX = MAX_BULLETS, '- '\ndef report(xs):\n    return xs[:SHOWN]\n"),
)

MUST_FLAG = tuple(e for e in ENTRIES if e[2])
NEGATIVE_CONTROLS = tuple(e for e in ENTRIES if not e[2])


# --- APPENDED 2026-08-02: the scalar-suffix families ------------------------
# The D2 no-regression gate MEASURED that without these the round-1 regression
# scores 1 lost of 18; with them it scores 14 of 67. The corpus could not see the
# regression it exists to catch. must_flag=True was verified by running the
# 1dcf430 baseline guard over each planted entry, not assumed from the name.
_SCALAR_SUFFIX_ENTRIES = (
    ('max_len_display',
     'hooks/max_len_display.py',
     True,
     'MAX_LEN = 12\n\n\ndef report(xs):\n    return xs[:MAX_LEN]\n'),
    ('max_len_collection',
     'hooks/max_len_collection.py',
     True,
     'MAX_LEN = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_LEN:\n            break\n        out.append(x)\n    return out\n'),
    ('max_bytes_display',
     'hooks/max_bytes_display.py',
     True,
     'MAX_BYTES = 12\n\n\ndef report(xs):\n    return xs[:MAX_BYTES]\n'),
    ('max_bytes_collection',
     'hooks/max_bytes_collection.py',
     True,
     'MAX_BYTES = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_BYTES:\n            break\n        out.append(x)\n    return out\n'),
    ('max_chars_display',
     'hooks/max_chars_display.py',
     True,
     'MAX_CHARS = 12\n\n\ndef report(xs):\n    return xs[:MAX_CHARS]\n'),
    ('max_chars_collection',
     'hooks/max_chars_collection.py',
     True,
     'MAX_CHARS = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_CHARS:\n            break\n        out.append(x)\n    return out\n'),
    ('max_seconds_display',
     'hooks/max_seconds_display.py',
     True,
     'MAX_SECONDS = 12\n\n\ndef report(xs):\n    return xs[:MAX_SECONDS]\n'),
    ('max_seconds_collection',
     'hooks/max_seconds_collection.py',
     True,
     'MAX_SECONDS = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_SECONDS:\n            break\n        out.append(x)\n    return out\n'),
    ('max_file_bytes_display',
     'hooks/max_file_bytes_display.py',
     True,
     'MAX_FILE_BYTES = 12\n\n\ndef report(xs):\n    return xs[:MAX_FILE_BYTES]\n'),
    ('max_file_bytes_collection',
     'hooks/max_file_bytes_collection.py',
     True,
     'MAX_FILE_BYTES = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_FILE_BYTES:\n            break\n        out.append(x)\n    return out\n'),
    ('max_line_chars_display',
     'hooks/max_line_chars_display.py',
     True,
     'MAX_LINE_CHARS = 12\n\n\ndef report(xs):\n    return xs[:MAX_LINE_CHARS]\n'),
    ('max_line_chars_collection',
     'hooks/max_line_chars_collection.py',
     True,
     'MAX_LINE_CHARS = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_LINE_CHARS:\n            break\n        out.append(x)\n    return out\n'),
    ('max_total_bytes_display',
     'hooks/max_total_bytes_display.py',
     True,
     'MAX_TOTAL_BYTES = 12\n\n\ndef report(xs):\n    return xs[:MAX_TOTAL_BYTES]\n'),
    ('max_total_bytes_collection',
     'hooks/max_total_bytes_collection.py',
     True,
     'MAX_TOTAL_BYTES = 12\n\n\ndef scan(xs):\n    out = []\n    for x in xs:\n        if len(out) >= MAX_TOTAL_BYTES:\n            break\n        out.append(x)\n    return out\n'),
)

ENTRIES = ENTRIES + _SCALAR_SUFFIX_ENTRIES
MUST_FLAG = tuple(e for e in ENTRIES if e[2])
NEGATIVE_CONTROLS = tuple(e for e in ENTRIES if not e[2])


# --- APPENDED 2026-08-06: caps OUTSIDE a function -----------------------------
# The second family derived from the PREDECESSOR's capabilities rather than the
# successor's, which the plan records as still owed.
#
# Every one of the 125 entries above wraps its cap in a `def`. The predecessor has no
# notion of a function at all - it walks the whole AST - so a rebuild that only ever
# looks inside functions loses all seven of these while the corpus reports parity.
# MEASURED, not reasoned: a real intermediate build of C1-NEW (function scopes only)
# was BLIND to 7 of 7 while the predecessor caught 7 of 7, and no_regression printed
# "predecessor saw 31 of 96, working tree sees 31". A detection regression that every
# gate in this repo would have passed.
#
# must_flag=True is baseline-verified the same way the scalar-suffix family was: each
# entry was planted and run against the live predecessor guard, not assumed from its
# name.
_MODULE_SCOPE_ENTRIES = (
    ('pred_module_level_display_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\nITEMS = list(range(50))\nSHOWN = ITEMS[:MAX_BULLETS]\n'),
    ('pred_module_level_collection_break',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\nOUT = []\nfor x in range(50):\n    if len(OUT) >= MAX_ITEMS:\n        break\n    OUT.append(x)\n'),
    ('pred_class_body_display_slice',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\n\n\nclass Report:\n    ROWS = list(range(50))\n    SHOWN = ROWS[:MAX_BULLETS]\n'),
    ('pred_slice_in_main_guard',
     'hooks/f.py',
     True,
     "import sys\nMAX_BULLETS = 12\nif __name__ == '__main__':\n    print(sys.argv[:MAX_BULLETS])\n"),
    ('pred_break_in_module_try',
     'hooks/f.py',
     True,
     'MAX_ITEMS = 10\nOUT = []\ntry:\n    for x in range(50):\n        if len(OUT) >= MAX_ITEMS:\n            break\n        OUT.append(x)\nexcept OSError:\n    pass\n'),
    ('pred_display_slice_in_a_lambda',
     'hooks/f.py',
     True,
     'MAX_BULLETS = 12\nhead = lambda xs: xs[:MAX_BULLETS]\n'),
    ('pred_function_local_max_used_at_module_level',
     'hooks/f.py',
     True,
     'def setup():\n    MAX_BULLETS = 12\n    return MAX_BULLETS\n\n\nROWS = list(range(50))\nSHOWN = ROWS[:MAX_BULLETS]\n'),
)

ENTRIES = ENTRIES + _MODULE_SCOPE_ENTRIES
MUST_FLAG = tuple(e for e in ENTRIES if e[2])
NEGATIVE_CONTROLS = tuple(e for e in ENTRIES if not e[2])


# --- APPENDED 2026-08-06: derived from the ACCEPTANCE CRITERIA ----------------
# A third provenance, and arguably the soundest of the three. The scalar-suffix family
# comes from the predecessor's CAPABILITIES and the module-scope family from the
# predecessor's SCOPE; this one comes from the RECORDED DEFECTS of the reverted detector
# ("a callee renamed by assignment must still resolve"), so it is biased toward neither
# guard.
#
# Found by probing the 8 acceptance criteria directly during the completeness audit.
# C1-NEW had REINTRODUCED that defect and still scored 100 of 103, because every existing
# entry renames a callee by IMPORT - a corpus cannot see a shape it has no entry for, and
# a score that does not move is not evidence that nothing broke. That is the whole
# argument for this family existing.
_ACCEPTANCE_ENTRIES = (
    ('callee_renamed_by_assignment',
     'hooks/f.py',
     True,
     'import itertools\ntake = itertools.islice\nMAX_BULLETS = 12\ndef report(xs):\n    return list(take(xs, MAX_BULLETS))\n'),
    ('callee_renamed_through_a_chain',
     'hooks/f.py',
     True,
     'import itertools\na = itertools.islice\nb = a\nMAX_BULLETS = 12\ndef report(xs):\n    return list(b(xs, MAX_BULLETS))\n'),
    ('neg_unrelated_assignment_rename',
     'hooks/f.py',
     False,
     'import os\np = os.path\ndef report(xs):\n    return p.join(*xs)\n'),
)

ENTRIES = ENTRIES + _ACCEPTANCE_ENTRIES
MUST_FLAG = tuple(e for e in ENTRIES if e[2])
NEGATIVE_CONTROLS = tuple(e for e in ENTRIES if not e[2])


def selftest() -> int:
    """The corpus checks ITSELF: unique names, non-empty sources, both classes populated."""
    fails = []
    names = [e[0] for e in ENTRIES]
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        fails.append("duplicate entry names: %s" % dupes)
    for e in ENTRIES:
        if len(e) != 4:
            fails.append("malformed entry: %r" % (e,))
        elif not e[3].strip():
            fails.append("entry %r has an empty source" % e[0])
        elif not e[1].endswith(".py"):
            fails.append("entry %r has a non-.py path %r" % (e[0], e[1]))
    if not MUST_FLAG:
        fails.append("no must-flag entries - the corpus cannot detect blindness")
    if not NEGATIVE_CONTROLS:
        fails.append("no negative controls - the corpus cannot detect a flag-everything guard")
    print("-- cap corpus: %d entries = %d must-flag + %d negative controls"
          % (len(ENTRIES), len(MUST_FLAG), len(NEGATIVE_CONTROLS)))
    for f in fails:
        print("SELFTEST FAIL:", f)
    print("SELFTEST OK" if not fails else "SELFTEST FAILED")
    return 0 if not fails else 1


if __name__ == "__main__":
    import sys as _s
    raise SystemExit(selftest() if "--selftest" in _s.argv else 0)
